name: Validate

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Typecheck
        run: npm run typecheck -- -p tsconfig.app.json

      - name: Run Linting
        run: npm run lint -- --max-warnings 0

      - name: Run Formatting
        run: npm run format -- --check
